### PR TITLE
feat: additional rust queries

### PR DESCRIPTION
**Pull request by Saecki**
Specify the end node on some queries and add some others.

### CODE REVIEW

**Comment by lewis6991** [comment]
Thanks!

**Comment by Saecki** [comment]
Oh, and I removed `expression_item`, forgot to write that down. Do you remember why you added it initially? I didn't find a use for it.

**Comment by Saecki** [comment]
Maybe for method chaining?

**Comment by lewis6991** [comment]
I don't really write rust so I have no idea why I added it. Maybe someone else did.

Without tests though, I'll basically merge anything that doesn't error.

**Pull request merged**
