### PR TITLE
fix(render): add missing window check - follow ups

### PR DESCRIPTION
**Pull request by przepompownia**

### CODE REVIEW

**Comment by przepompownia** [comment]
I'm not sure if the check should be performed here. 

Notice another unchecked `api.nvim_win_get_buf` 17 lines below this change. I haven't caught the invalid window error there yet.

**Comment by przepompownia** [comment]
Browsing conflicts with Diffview can expose such errors.

**Comment by przepompownia** [comment]
[this place](https://github.com/nvim-treesitter/nvim-treesitter-context/blob/6cba006378b0ca68a66ea54153c0113724c91753/lua/treesitter-context/render.lua#L415) still waits for catch…

**Comment by apollo1321** [comment]
> https://github.com/nvim-treesitter/nvim-treesitter-context/blob/6cba006378b0ca68a66ea54153c0113724c91753/lua/treesitter-context/render.lua#L415
> 
> This place still waits for catch…

How is it possible that the context window is valid, but its buffer has somehow become invalid?

**Comment by przepompownia** [comment]
> How is it possible that the context window is valid, but its buffer has somehow become invalid?

Right, I didn't notice that the value mentioned earlier as uncaught is validated in the second commit :grinning:

**Pull request merged**
