### PR TITLE
feat: allow passing param depth to go_to_context()

### PR DESCRIPTION
**Pull request by Bekaboo**
Implement #276.

### CODE REVIEW

**Comment by Bekaboo** [comment]
@lewis6991 Any thoughts / advice on this?

**Comment by amaanq** [comment]
Hmm, doesn't vim.iter break 0.8.2 compatibility (not that I care, tree-sitter stuff is experimental anyways, just double checking)

**Comment by Bekaboo** [comment]
> Hmm, doesn't vim.iter break 0.8.2 compatibility (not that I care, tree-sitter stuff is experimental anyways, just double checking)

@amaanq Good point, will fix this later. Also, do you think that it is better to use `vim.v.count1` as the fallback of `depth`?

**Comment by amaanq** [comment]
Sorry about the delay - I wasn't aware that that's a thing, but is that not just 1?

**Comment by lewis6991** [comment]
Will merge if this is updated and fixed. Otherwise I'll close this as stale.

**Comment by Bekaboo** [comment]
@lewis6991 Sorry for the latency, please don't close this. I am interested in improving this PR but quite busy this week. Will work on this in two weeks or so.

**Comment by Bekaboo** [comment]
@lewis6991 @amaanq Removed usage of `vim.iter()` and solved conflicts with `master`

**Pull request merged**
