### PR TITLE
chore: add CI

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by lewis6991** [comment]
@romgrk do you know how to enable GH actions?

**Comment by romgrk** [comment]
Do they need enabling? Isn't merging this enough?

**Comment by romgrk** [comment]
The config you're passing says to only run for `main` branch, probably that's why it doesn't run? Also note the default branch is `master` here, not `main`.

**Review by romgrk — APPROVED** [review]
All good :)

**Pull request merged**
