### PR TITLE
feat!: use queries for determining context

### PR DESCRIPTION
**Pull request by lewis6991**
This plugin has been significantly rewritten to use Treesitter queries instead of patterns for determining context regions for languages.

The main benefits of this change are:
- it is a much simpler implementation since we can leverage core APIs.
- it fits in more generally with the Treesitter eco-system.
- it allows configuration of contexts to be provided from multiples sources.
- it allows more sophisticated configuration of contexts since queries (with directives and predicates) are much more powerful than patterns.
- the query format should be usable for other editors.

The major downside of this new implementation is that it requires each language to provide it's own query as opposed to using the general purpose patterns. This means that some languages which had contexts before may not have them now. If this is the case then please raise an issue. Adding queries for a specific language is fairly simple but too much work to implement for all 170+ parsers that exist.

This commits provides explicit support for:
  - bash
  - c
  - cpp
  - typescript
  - rust
  - json
  - lua
  - markdown
  - python
  - yaml
  - php
  - scala
  - teal
  - toml
  - vim

Please see the README for instructions on how to add support for other languages.

This commit also drops explicit support for Nvim 0.7. If you still need support for this version then you can use the `compat/0.7` release.

### CODE REVIEW

**Comment by syphar** [comment]
this is awesome :) 

I'm happy to help testing / reviewing, if needed. 

Could this also somehow handle the `last_nodes` logic through different queries? 

( I only have basic knowledge of TS queries, so I'm not sure).

**Comment by lewis6991** [comment]
I hope so. I don't fully understand the `last_nodes` stuff, so need to get my head around it.

**Comment by lewis6991** [comment]
> I'm happy to help testing / reviewing, if needed.

Yes please. Any help is welcome.

This is a huge breaking change so I'll just be daily driving this branch for a while.

**Comment by lewis6991** [comment]
Yeah, I don't really understand the last nodes stuff. Can you provide an example of what it does (or should do) and I'll just implement it with queries?

**Comment by lewis6991** [comment]
Yeah not sure tbh, we'll see.

The goal here is that all language specific stuff is handled in queries and we just define some standard captures. `last_node` probably makes sense as a capture.

**Comment by syphar** [comment]
about last_nodes I have two examples from python, to start with ( see also #92 and #171), both related to multi-line nodes: 

```python
def set_position(
    self,
    app_label,
    model_name,
    pk
) -> SomeClass:
    ...
```

```python
class Customer(
    PrivateDataMixin,
    PersonMixin,
    TitleSalutationMixin,
    CommentableMixin,
    DirtyFieldsMixin,
    OptionalBaseAddress,
    UserAgentMixin,
):
    # ...

```

In both cases, when the class or the method is outside of the view, the old context implementation would merge all the lines until it reaches any node not in `last_nodes` (I think), so the context would show the whole definition including the return-type (for the function) or including the base-classes (for the class definition).

**Comment by syphar** [comment]
while playing around with queries I saw that the current implementation will actually merge the whole TS node content into one line, which for the python function example (`function_definition`) will lead to the whole function body being added too.

**Comment by syphar** [comment]
reading longer, it could be that `#make-range!` ( from treesitter-textobjects ) would help here? 

( while the problem where would be that the `def` at the beginning of the function definition wouldn't be included in context, assuming we're trying to write a query that includes only the definition of the function, not the body

**Comment by lewis6991** [comment]
I've got a rough idea to solve this by just adding a second capture (or reuse `@context`) to a match that will be used to control what gets displayed.

**Comment by lewis6991** [comment]
Just looked at the `last_node` stuff and can't seem to replicate the issue.

**Comment by lewis6991** [comment]
Figured it out and implemented it in queries. Need to use `context.final` (final node) or `context.end` (exclude from context) within a single match.

**Comment by syphar** [comment]
> Figured it out and implemented it in queries. Need to use `context.final` (final node) or `context.end` (exclude from context) within a single match.

This sounds awesome! 

I'm on the road this week but I'll find time over the weekend or next week to do some testing around it, in the languages I'm using.

**Comment by syphar** [comment]
I did a small check with python, the `context.end` thing seems to work :) 

One thing I saw, not sure if this is a bug: 
grafik

The same code piece with `master`: 
grafik

( the hilighting is gone in the first example)

**Comment by syphar** [comment]
@lewis6991 I'm happy to provide queries for the languages I'm using, if needed. Otherwise I'll do this when the base logic is finished.

**Comment by lewis6991** [comment]
The multiline thing makes the highlighting a complete hack and fragile. Not really sure of a robust way to support highlighting AND multiline.

Highlighting basically works by parsing the main buffer and applying highlights to the context with some fragile logic to account for when the lines are joined with the whitespace trimmed.

**Comment by syphar** [comment]
Hilighting was also fine when I added `context.end`, so more nodes were included in the context. 

Then let's see how this goes with more queries :)

**Comment by lewis6991** [comment]
Yes more queries please.

Raise a PR with the files and I'll cherry pick them here.

**Comment by lewis6991** [comment]
I think I understand the highlighting issue, I'll fix next.

**Comment by syphar** [comment]
@lewis6991 after the last bugfix I started to use this branch in my day-to-day work, 

here are some new queries: 
- https://github.com/syphar/nvim-treesitter-context/commit/be095a3e9676f2eb3ef448c600f94f5b91dfb7e9
- https://github.com/syphar/nvim-treesitter-context/commit/a8dcf1501d5d926b56e64e00e338f295eadc0ffc

I'm not sure if every user would like the `expression_statement` pieces in there, for me it belongs into the context. 

For example in a multi line function call this would give me the first line of the call: 
grafik

**Comment by lewis6991** [comment]
Updates both.

**Comment by lewis6991** [comment]
@romgrk I'm thinking of merging this fairly soon. Can you have a look?

**Pull request merged**
