### PR TITLE
feat: show trailing return types

### PR DESCRIPTION
**Pull request by Saecki**
This shows trailing return types in rust, python, and typescript by querying named fields of the function nodes. I don't know if this is the preferred way to implement this or if one would use queries (I have never touched that), but it seems to work quite well.

### CODE REVIEW

**Comment by romgrk** [comment]
Can you show examples of this? Before/after, and some code that I can test this with?

**Comment by Saecki** [comment]
Sure, I will add more code the other languages later.

## Rust
```rs
fn abc(a: bool) -> char {
    return '0';
}
```
Previously: `fn abc(a: bool)`
Now: `fn abc(a: bool) -> char`

## Python
```py
def abc(a: bool) -> str:
    return '0'
```
Previously: `def abc(a: bool)`
Now: `def abc(a: bool) -> char`

**Review by lewis6991 — APPROVED** [review]
A lot of these changes make me a little nervous, but this looks ok.

We should probably add some CI.

**Comment by Saecki** [comment]
Yeah CI would be a good idea.

I forgot to mention methods above, before there weren't any last node types for methods, so just the first line was shown, now these should behave the same as functions:

## Lua
```lua
function M:abc()
     return false
end
```

## Javascript
```js
class M {
    function abc() {
        return false
    }
}
```

## Typescript
```ts
class M {
    function abc(): boolean {
        return false
    }
}
```

**Comment by Saecki** [comment]
It would probably make sense to add some last node types or named fields for classes, loops, etc.

**Comment by Saecki** [comment]
The last commit allows to query node types and field names. Let me know what you think of it, missing queries for other languages can be added later.

**Comment by romgrk** [comment]
> A lot of these changes make me a little nervous, but this looks ok.
> 
> We should probably add some CI.

@lewis6991 Same feeling here. I originally used lua patterns instead of hardcoding the groups for simplicity, but I'm always afraid it'll catch stuff it shouldn't. 
Do you have a propostion for CI? Not sure how to do it for a neovim plugin. The neovim codebase does have a nice testing setup to test UI & events from the user side, but it looks dauting to put in place for a plugin.

> It would probably make sense to add some last node types or named fields for classes, loops, etc.
> The last commit allows to query node types and field names. Let me know what you think of it, missing queries for other languages can be added later.

@Saecki If It's not too much work and you have some free time, would you be able to expand a bit the supported nodes/languages? For glaring bugs, I trust users will report them, but for more subtle improvements such as this one, it's unlikely to change much. If you don't have enough time but have improvement ideas, don't hesitate to open a new issue so we document possible improvements.
Other than that, it also LGTM, I'm ok with merging as is.

**Comment by lewis6991** [comment]
> Do you have a propostion for CI? Not sure how to do it for a neovim plugin. The neovim codebase does have a nice testing setup to test UI & events from the user side, but it looks dauting to put in place for a plugin.

I've already done it for 3 plugins so I have a good idea on how to do it. I've raised #127 (WIP). Basically, we just clone neovim and add our own spec files.

**Comment by romgrk** [comment]
@Saecki This is ready to be merged?

**Comment by Saecki** [comment]
Yes

**Pull request merged**
