### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vhoyer**
Might be obvious, for me it wasn't, I thought somehow this plugin would just work out of the box, it's the first time I actually interact with anything tree-sitter, so... :sweat_smile:

### CODE REVIEW

**Comment by lewis6991** [comment]
nvim-treesitter isn't required for this plugin. nvim-treesitter is just required to get extra parsers.

**Comment by vhoyer** [comment]
Really? Oh sorry then, but this works out of the box for what languages? 🤔

**Comment by lewis6991** [comment]
On nvim master:

```
bash.so  c.so  lua.so  markdown.so  markdown_inline.so  python.so  query.so  vim.so  vimdoc.so
```

Can't remember what languages are bundled in 0.9.5. I think just C and Lua.

**Comment by vhoyer** [comment]
I see, so then maybe can we mention something like that on the `Supported Languages` secion? I think it could help :)

**Comment by lewis6991** [comment]
Thanks, but I think I'll pass.

**Comment by vhoyer** [comment]
oh, ok then, thanks for the attention

**Pull request closed without merging**
