### PR TITLE
fix: selected minus row, early return

### LINKED ISSUE #442: Crash on empty first line when number line is on (markdown)
### Description

With `vim.opt.number = true`, while editing a markdown file where the first line is empty, the plugin will crash when you have scrolled far down enough for the context line to trigger.

### Neovim version

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1713773202     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"

### Expected behavior

Single empty context line on top

### Actual behavior

```
Error detected while processing CursorMoved Autocommands for "*":                                                               
Error executing lua callback: /tmp/nvim/site/ts_context/lua/treesitter-context/render.lua:106: Could not apply exmtark to { -1, 0 }: Invalid 'line': out of range
stack traceback:
        [C]: in function 'error'
        /tmp/nvim/site/ts_context/lua/treesitter-context/render.lua:106: in function 'add_extmark'
        /tmp/nvim/site/ts_context/lua/treesitter-context/render.lua:235: in function 'highlight_bottom'
        /tmp/nvim/site/ts_context/lua/treesitter-context/render.lua:303: in function 'render_lno'
        /tmp/nvim/site/ts_context/lua/treesitter-context/render.lua:353: in function 'open'
        /tmp/nvim/site/ts_context/lua/treesitter-context.lua:50: in function 'open'
        /tmp/nvim/site/ts_context/lua/treesitter-context.lua:111: in function 'f'
        /tmp/nvim/site/ts_context/lua/treesitter-context.lua:27: in function </tmp/nvim/site/ts_context/lua/treesitter-context.lua:21>
```

### Minimal config

```Lua
local plugins = {
  ts         = 'https://github.com/nvim-treesitter/nvim-treesitter',
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.o.runtimepath = install_path..','..vim.o.runtimepath
end

vim.opt.number = true
```

### Steps to reproduce

[example.md](https://github.com/nvim-treesitter/nvim-treesitter-context/files/15319707/example.md)

1. `nvim --clean -u minimal.lua example.md`
2. `:TSInstall markdown`
3. `G` (go to bottom)

### PR DESCRIPTION
**Pull request by yanskun**
It's a bit rough, but I tried to resolve #442.

Apparently, there are cases where line -1 is specified.
So, in that case, I tried not to process it.

### CODE REVIEW

**Comment by sumnerevans** [comment]
This fixes the crash, but it ends up showing a blank line when it should probably show no line.

An example of a file that exhibits this behavior is: https://github.com/sumnerevans/sumnerevans.com/blob/master/content/posts/travel/2024-scale/index.md

It worked correctly in the frontmatter:

image

But then when I scroll down into the body of the file, then it does this:

image

**Comment by yanskun** [comment]
Oh, I reproduced it, sorry.
Thanks to Debug.
I'll try it some more!

**Comment by c60cb859** [comment]
I can confirm that this fixed the same issue for me when markdown files had a meta section in the top
```
+++
foo
+++
```

**Comment by YakBarber** [comment]
This works for me for on Nvim 0.10.0 with "Obsidian"-style markdown meta frontmatter:

```---
id: template
aliases: []
tags: []
---
```

I can also confirm the blank line behavior mentioned above.

**Pull request closed without merging**
