### PR TITLE
Revert multiwindow support

### PR DESCRIPTION
**Pull request by lewis6991**
Too buggy, needs more development.

This reverts commit f1b728501ef263d1cf344263c675d7d146a15239.
This reverts commit e7fdb4cdf0942cd6e63dd822110a93c0ec777fe5.
This reverts commit 9e36638afd4dcc06bc94a661940f3648ce067da2.
This reverts commit 6cba006378b0ca68a66ea54153c0113724c91753.
This reverts commit bf6386d9bbb9e53386987beb90264abd4faf5c74.
This reverts commit 3de5708b3060554ba5f383404f2ce6516e9dbed1.
This reverts commit 63374d1c36050fdea7a773aa4125b45e9a8da8f5.

### CODE REVIEW

**Comment by lewis6991** [comment]
https://github.com/lewis6991/satellite.nvim manages multi window pretty well. Never had an issue with it. Maybe you can take a look at that.

**Comment by apollo1321** [comment]
Okay, I think I know how to fix two existing bugs (https://github.com/nvim-treesitter/nvim-treesitter-context/issues/522 and https://github.com/nvim-treesitter/nvim-treesitter-context/issues/512#issuecomment-2448422407). Will you give me until the end of the weekend to fix them? Is there anything else you would like to fix besides the two existing problems?

**Comment by lewis6991** [comment]
I'm seeing issues my side too. Not sure if they are the same issues, but I've not got bandwidth to debug them.

**Comment by lewis6991** [comment]
I can wait a week for you to apply some fixes and see if that addresses the issues. Would that be ok or shall I revert now?

**Comment by apollo1321** [comment]
Sounds great, thanks. I'm already fixing it now, I'll bring the PR soon.

**Comment by lewis6991** [comment]
Things feel more stable now. Closing.

**Pull request closed without merging**
