### PR TITLE
fix: set "fillchar" for 'statuscolumn' rendering

### LINKED ISSUE #396: The `stl` setting from `'fillchars'` is being displayed in ts-context when using `'statuscolumn'`
### Description

When I `:set fillchars=stl:#`, I'm seeing those chars inside of ts-context: 
2024-02-16_12-28-44_region

This happens when I am using a custom `statuscolumn`.

### Neovim version

v0.10.0-dev-2371+gd60eeacae4

### Expected behavior

Fillchars shouldn't be visible in ts-context.

### Actual behavior

Fillchars are visible in ts-context.

### Minimal config

```Lua
local plugins = {
  ts = "https://github.com/nvim-treesitter/nvim-treesitter",
  ts_context = "https://github.com/nvim-treesitter/nvim-treesitter-context",
  -- ADD ADDITIONAL PLUGINS THAT ARE _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = "/tmp/nvim/site/" .. name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
  end
  vim.o.runtimepath = install_path .. "," .. vim.o.runtimepath
end

require("nvim-treesitter.configs").setup({
  ensure_installed = {
    "javascript",
  },
})
require("treesitter-context").setup({})

vim.o.number = true
vim.o.relativenumber = true
vim.o.statuscolumn = "%=%r%= "
vim.o.fillchars = "stl:#"
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. open a file and check out the ts-context behavior

### PR DESCRIPTION
**Pull request by luukvbaal**
Fix #396

### CODE REVIEW

**Comment by luukvbaal** [comment]
Doesn't matter much but this argument will not be used in 0.10. Care for a comment like this?

```lua
fillchar = ' ',  -- may be removed once earliest supported version is 0.10
```

**Comment by lewis6991** [comment]
Can you attach the link to the issue and say fixed in 0.10.

**Comment by luukvbaal** [comment]
Sure, actual link or issue number?

**Comment by lewis6991** [comment]
Issue number should be fine.

**Comment by lewis6991** [comment]
Thanks a bunch

**Pull request merged**
